// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtm7Aio4UXpbTYcCi_2CBRSMRuQGItPZo',
    appId: '1:806216671042:android:e8ec638a779d7895b8b2db',
    messagingSenderId: '806216671042',
    projectId: 'resqbox-2740d',
    storageBucket: 'resqbox-2740d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmseVnoHlY8yDFYyhWBaUTCqYAagGtnCc',
    appId: '1:806216671042:ios:13c61fc7cd0d6347b8b2db',
    messagingSenderId: '806216671042',
    projectId: 'resqbox-2740d',
    storageBucket: 'resqbox-2740d.firebasestorage.app',
    androidClientId: '806216671042-16e5qhc94bfkuhuor9jq6mctom012ugc.apps.googleusercontent.com',
    iosClientId: '806216671042-5v4na1bvv3h36qvmdnugbrhie0vj5cov.apps.googleusercontent.com',
    iosBundleId: 'com.user.resqbox',
  );
}
